### ISSUE TITLE
Registering name for wallet.

### ISSUE THREAD

**Issue by madasretisireh** [IBAX-io/go-ibax#1004]
### Clear and concise description of the problem

I found that there is no feature to register wallet addresses with name in order to send from wallet. This can be added.

### Suggested solution

We need a tab that allows us to register our wallet addresses.

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ibaxio** [comment]
We have actually implemented the ability to transfer money using nicknames, which you can test out in weaver.
