### ISSUE TITLE
Ibax mobil cüzdan yüzü 

### ISSUE THREAD

**Issue by ozgur190734** [IBAX-io/go-ibax#102]
### Clear and concise description of the problem

Merhaba arkadaşlar.
İbaxın mobil cüzdan yüzü daha detaylı olabilir aslında.
https://weaver.ibax.io/  adresine girdiğimizde seçeneklerin bol olduğu menü görmek istiyoruz. Umarım geliştirici seçeneklerle gelir önümüzdeki günlerde. 

### Suggested solution

Cüzdan mobil yüzü detaylı seçenekli Bir sürüm olabilir. Teşekkürler 

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ysfcndgr** [comment]
"Cüzdan mobil yüzü detaylı seçenekli Bir sürüm olabilir" bundan kastınız nedir? Sorununuzu daha detaylı açıklamayı deneyin
