### ISSUE TITLE
HOW MORE IBAX POINTS?? QUESTION ANSWER SEE

### ISSUE THREAD

**Issue by balkes222** [IBAX-io/go-ibax#1021]
### Clear and concise description of the problem

HOW MORE IBAX POINTS??

### Suggested solution

PERFORMING IBAX TASKS

### Alternative

PERFORMING IBAX TASKS
AND YOUR COMMENTS

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ibaxio** [comment]
Follow the instructions in the Member Centre.

Keep an eye on the Member Centre as our events will be posted on it as soon as they are available.

Thanks!
