### ISSUE TITLE
İbax çok geç açılıyor çözüm 🙏

### ISSUE THREAD

**Issue by Silopili** [IBAX-io/go-ibax#103]
### Describe the bug

Çok ağır site

### Reproduction

Yok

### System Info

```shell
.
```

### Logs

```shell
Ağır bir site
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Emredurmus27** [comment]
Çok mu yüklenme var acaba neden bu kadar yavaş site

**Comment by ysfcndgr** [comment]
Aşırı yoğunluk olduğu zamanlarda bu tür teknik aksaklıklar olabilir
