### ISSUE TITLE
Ibax

### ISSUE THREAD

**Issue by riskymuhamad99** [IBAX-io/go-ibax#1031]
### Describe the bug

it needs to be refreshed several times for the coin to appear, and it happened again and again when I logged in.. hopefully it can be resolved

### Reproduction

Good

### System Info

```shell
Good
```

### Logs

```shell
Good
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ibaxio** [comment]
Problems with Internet connection, please try again. thanks.
