### ISSUE TITLE
Retweet yaptığım halde puan gelmemesi

### ISSUE THREAD

**Issue by oouzhans** [IBAX-io/go-ibax#106]
### Describe the bug

Tweeti retweet yaptım fakat tekrar deneyin hatası aldım. Tekrar denedim fakat puanlarımı vermedi. 
![273A00FC-825B-49C3-B08D-0BD26A764D2B](https://user-images.githubusercontent.com/98263136/150677922-0c7edeb8-37ba-4e9b-858b-904c555bb1cd.png)

### Reproduction

![F0602C87-DD04-42A4-B25E-BBDEEED0D665](https://user-images.githubusercontent.com/98263136/150677946-630e59a3-115e-4c90-bbc4-cbdf6e4cdce5.png)

### System Info

```shell
Browsers
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by semihcantali** [comment]
aynı sorun bende de var çözümü bilen varsa yardımcı olabilir mi

**Comment by ysfcndgr** [comment]
Twitter API hakkı bittiği için IBAX tarafından gerçekleşen bir sorundur ancak endişelenmeyin son gelen görevler sayılmayacak ve sıralama tekrardan belirlenecektir.
