### ISSUE TITLE
Türkçe Dil

### ISSUE THREAD

**Issue by muhmmedcelik** [IBAX-io/go-ibax#1078]
### Clear and concise description of the problem

Lütfen Türkçe Dil destegi gelsin .

### Suggested solution

Lütfen Türkçe Dil destegi gelsin .

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Efsane4167** [comment]
Elbette turkce dil olur kesinliklr gelir 
.

**Comment by VuNgo91** [comment]
hi

**Comment by Vetkartal05** [comment]
Türkçe dil desteği önemli

**Comment by ccksoner** [comment]
önemli
