### ISSUE TITLE
İbax blockchain nice project

### ISSUE THREAD

**Issue by Can21can** [IBAX-io/go-ibax#1088]
### Clear and concise description of the problem

Ywh1gb2hsjjsmdhdbvdg

### Suggested solution

Bebdbdbx bd

### Alternative

ZbbdbzkqmBrbej ve mdsbz vr DDR3 vd ebhs

### Additional context

Zbbwyhqgdakwlzbc 2jbdbevgdg de t2gwhhtikabghbd

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Davut4** [comment]
Iyı proje

**Comment by husnusezer** [comment]
Nasıl olacak kaç verecek acaba

**Comment by besir02** [comment]
Gelecek gibi çin devam
