### ISSUE TITLE
guide with training videos 

### ISSUE THREAD

**Issue by Modelactor** [IBAX-io/go-ibax#110]
### Clear and concise description of the problem

Publishing training videos will be effective for solving wallet-related problems.

### Suggested solution

constantly guiding them with short and concise videos through social media.

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ysfcndgr** [comment]
Follow Ibax Youtube Channel
https://www.youtube.com/channel/UC-oneUwzz01xaCkFTTyR0QQ
