### ISSUE TITLE
türkçe dil desteği

### ISSUE THREAD

**Issue by 8nokta2** [IBAX-io/go-ibax#1103]
### Clear and concise description of the problem

lütfen uygulama için türkçe dil desteği gelsin inanın çok fazla Türk kullanıyor uygulamayı

### Suggested solution

türkçe dil desteği

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ugurpehlivanoglu** [comment]
süper

**Comment by Vetkartal05** [comment]
çok haklı bir istem

**Comment by baskivani** [comment]
Türkiye, dünya kripto piyasalarında en fazla yatırım yapan 4. ülke konumunda. Bu nedenle İbax'ın Türkçe dil desteği olması çok faydalı olacaktır.

**Comment by Sercan5959** [comment]
Hesabima giris yapamiyorum 15 kelime var giriyom sifreyi giriyom gecersiz diyor

**Comment by ankateam41** [comment]
katılıyorum

**Comment by ysfcndgr** [comment]
Türkçe dil desteği hazırlanıyor yakın zamanda sitemize entegrasyon gerçekleşecek.

**Comment by M-Clk** [comment]
Update gelmeden issue acik kalsın lütfen.

**Comment by ysfcndgr** [comment]
Türkçe dil desteği entegre edilmiştir konuyu kapatıyorum.
