### ISSUE TITLE
PUANLARIM GÖZÜKMÜYOR 0 YAZIYOR

### ISSUE THREAD

**Issue by jesuscoo** [IBAX-io/go-ibax#1109]
### Describe the bug

GÖREVLERİN HEPSİNİ YAPTIM(RETWEET) ANCAK PUANLARIM GELMEDİ

### Reproduction

PUAN GELMEDİ

### System Info

```shell
PUAN
```

### Logs

```shell
go-ibax go-ibax start --test
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Vetkartal05** [comment]
rt yaptıktan sonra sayfada finished yaptın mı

**Comment by Ender35** [comment]
Sayfayı yenile

**Comment by ankateam41** [comment]
refresh yap

**Comment by CODOMAN** [comment]
Sayfa yenile İngilizce'de kal görünür.

**Comment by ysfcndgr** [comment]
Sayfayı yenileyin ve puanlarınızın geldiğinden emin olun.
