### ISSUE TITLE
Google play indirme 

### ISSUE THREAD

**Issue by asikral27** [IBAX-io/go-ibax#111]
### Clear and concise description of the problem

İbax uygulaması ve cüzdan indirme yok bunlar neden yapılmıyor? 

### Suggested solution

Google Play'de indirme yapılması gerek 

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by xeco12** [comment]
Bencede olamsi lazım

**Comment by ysfcndgr** [comment]
En yakın sürede gerekli entegrasyonlar yapılacaktır.
