### ISSUE TITLE
İbax puanları neden göremiyorsun!! 

### ISSUE THREAD

**Issue by Githubcem** [IBAX-io/go-ibax#1112]
### Describe the bug

İbax sayfasını tarayıcıdan açıyorsunuz?
Sayfayı Türkçe'ye çevirirseniz bu hata gelir.
Taramayı tamamlamasını temizleme adını ve şifresini tekrar gir düzeltebilir

### Reproduction

İbax sayfasını tarayıcıdan açıyorsunuz?
Sayfayı Türkçe'ye çevirirseniz bu hata gelir.
Taramayı tamamlamasını temizleme adını ve şifresini tekrar gir düzeltebilir

### System Info

```shell
İbax sayfasını tarayıcıdan açıyorsunuz?
Sayfayı Türkçe'ye çevirirseniz bu hata gelir.
Taramayı tamamlamasını temizleme adını ve şifresini tekrar gir düzeltebilir
```

### Logs

```shell
İbax sayfasını tarayıcıdan açıyorsunuz?
Sayfayı Türkçe'ye çevirirseniz bu hata gelir.
Taramayı tamamlamasını temizleme adını ve şifresini tekrar gir düzeltebilir
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by balkes222** [comment]
When you translate the page into English, you will see your IBAX scores.
