### ISSUE TITLE
İbaxda puan nasıl toplanır?? 

### ISSUE THREAD

**Issue by Githubcem** [IBAX-io/go-ibax#1114]
### Clear and concise description of the problem

Benim de takip ettiğim bir kanal güzel airdrop  bilgileri veriyor tavsiye ederim bu konu hakkın da da biraz bilgi verilmiştir sayfasında

https://youtu.be/Z_ToGMnH8W4

### Suggested solution

https://youtu.be/Z_ToGMnH8W4

### Alternative

https://youtu.be/Z_ToGMnH8W4

Hiç yoktan iyidir 

### Additional context

https://youtu.be/Z_ToGMnH8W4

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ayken0713** [comment]
Geleceği olm bir coinbase

**Comment by ahmetnur99** [comment]
Çok iyi bir proje

**Comment by Face19951995** [comment]
İnsallaj kazaniriz

**Comment by Ufuk122** [comment]
Herkes bunu bekliyor

**Comment by dervishh** [comment]
heyecanla bekliyorum.

**Comment by kebuter77** [comment]
Umarım kazanırıx

**Comment by CODOMAN** [comment]
Retfet,beğen,önüne gelene finiş bitti de,arkadaş etiketle discord twet paylaş puan gelir 1 şubat para coin olacak.100/10 açılacak tamamen borsaya 5,6 ay sonra girecek.

**Comment by Coskun92** [comment]
21000 civar github kaç puan veriyor acaba?

**Comment by oolukman** [comment]
Github dan nasıl puan kazanacağız

**Comment by MstfYtskn** [comment]
Github biraz karışık gibi ya

**Comment by MstfYtskn** [comment]
> ### Clear and concise description of the problem
> Benim de takip ettiğim bir kanal güzel airdrop bilgileri veriyor tavsiye ederim bu konu hakkın da da biraz bilgi verilmiştir sayfasında
> 
> https://youtu.be/Z_ToGMnH8W4
> 
> ### Suggested solution
> https://youtu.be/Z_ToGMnH8W4
> 
> ### Alternative
> https://youtu.be/Z_ToGMnH8W4
> 
> Hiç yoktan iyidir
> 
> ### Additional context
> https://youtu.be/Z_ToGMnH8W4
> 
> ### Validations
> * [x]  Read the [docs](https://docs.ibax.io).
> * [x]  Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

Puan nasıl toplanır Githubdan
