### ISSUE TITLE
Gift

### ISSUE THREAD

**Issue by Diyaryilmaz** [IBAX-io/go-ibax#117]
### Clear and concise description of the problem

İbax'ın daha fazla kullanici cekmesi ve varolan kullanicilarinin daha iyi bir deneyim sahibi olabilmesi icin gift yani hediye ozeligi yok

### Suggested solution

Benim onerim ibax bir gift yani hadiye bolumu olusturmali bu bolumde kullanicilar arkadaslarina yada ailelelerine hediye olarak ibxc yada ibax puanini gonderebilecekler bu sayede site daha da kullanisli olacak

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ysfcndgr** [comment]
Mevcut olan sistemde zaten kendiniz ibaxlarınızı gönderebilirsiniz bunun için hediye sistemi gibi bir entegrasyona gerek yok.
