### ISSUE TITLE
Merhaba arkadaşlar.

### ISSUE THREAD

**Issue by Silopili** [IBAX-io/go-ibax#122]
### Clear and concise description of the problem

İbaxın site daha düzgün olabilir çok karmaşık retweetlerin puanları gelmiyor bazen oraya buraya basıyorsun hata veriyor

### Suggested solution

Lütfen bu buglar yapılsın

### Alternative

Lütfen

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Usc0404** [comment]
Merhaba

**Comment by xpro1990** [comment]
Fazla Bi bug yok sitede gayet güzel ve seri

**Comment by ysfcndgr** [comment]
Sitede herhangi bir sorun yok son gelen twitter görevlerinde Twitter APIsinden kaynaklı olarak hata alınıyordu. Son görevler kaldırıldı ve sıralama yeniden yapılacak.
