### ISSUE TITLE
Bir tane uygulama yapılırsa daha güzel olur platform birazcık karmaşık 

### ISSUE THREAD

**Issue by YUSF10** [IBAX-io/go-ibax#1301]
### Describe the bug

Platform biraz daha geliştirilip bı uygulama üzerinde yapılabilir 

### Reproduction

//

### System Info

```shell
//
```

### Logs

```shell
//
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Coskun92** [comment]
Bende buna katılıyorum. Daha güvenli hale gelicektir.
