### ISSUE TITLE
Uygulama

### ISSUE THREAD

**Issue by YUSF10** [IBAX-io/go-ibax#1302]
### Clear and concise description of the problem

Karmaşık bir platform

### Suggested solution

Uygulama yazılımı üzerinde yapılabilir platformda baya karmaşık

### Alternative

İbax

### Additional context

İbxm

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by fahrenayt34** [comment]
Arayüz biraz daha basitleştirilmiş olabilir
