### ISSUE TITLE
No problem

### ISSUE THREAD

**Issue by Mahbub3** [IBAX-io/go-ibax#1343]
### Describe the bug

How to open a wallet without 15 words?
Question answer

### Reproduction

How to open a wallet without 15 words?
Question answer

### System Info

```shell
How to open a wallet without 15 words?
Question answer
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

_Originally posted by @balkes222 in https://github.com/IBAX-io/go-ibax/discussions/1054_

**Comment by ysfcndgr** [comment]
Unfortunately, you cannot open your wallet.
