### ISSUE TITLE
Bence ibax sitesi arayüzü cok ağır degismesi lazim türkçe dil destegi lazim cok berbat şuanki hali daha iyi bir uygulamaya ihtiyacı var

### ISSUE THREAD

**Issue by Oktayy72** [IBAX-io/go-ibax#1358]
### Describe the bug

Uygulamankz cok kötü suan cok lag donma  var kaliteli bir site tasarlayicisina ihtiyaciniz var

### Reproduction

Sory

### System Info

```shell
Sory
```

### Logs

```shell
Sory
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by voddah28** [comment]
ok
