### ISSUE TITLE
Konu basina rutbe kasma?

### ISSUE THREAD

**Issue by Majezikonline** [IBAX-io/go-ibax#1386]
### Clear and concise description of the problem

Actigimiz konularin basina ibax rutbemiz arttiriliyor mu?

### Suggested solution

Konu basina mi acilan sandiktan hediyeler veriliyor

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Halo0642** [comment]
Bu konuyu bende merak ediyorum

**Comment by coinvaleo** [comment]
Rutbe olayını bir ben mi beceremedim.

**Comment by ysfcndgr** [comment]
Hayır arttırılmıyor.
