### ISSUE TITLE
Turklere ayricalik

### ISSUE THREAD

**Issue by Majezikonline** [IBAX-io/go-ibax#1392]
### Clear and concise description of the problem

Forumdaki konularin tamamini turkler olusturuyor 😄 

### Suggested solution

Türk kullanıcılara özel ayrıcalık tanınması gerek👍

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by burdurhasan86** [comment]
puan kaç paraya denk gelecek

**Comment by coinvaleo** [comment]
Bu şekilde devam edersek hintlileri gececez. Her airdrop da turkler hintliler ile kapışıyoruz.
 80milyon vs. 1.2 milyar

**Comment by Majezikonline** [comment]
> puan kaç paraya denk gelecek

Belli degil kimse bisey bilmiyor dostum

**Comment by Majezikonline** [comment]
> Bu şekilde devam edersek hintlileri gececez. Her airdrop da turkler hintliler ile kapışıyoruz. 80milyon vs. 1.2 milyar

Hahahahhahah aynen valla 😂
