### ISSUE TITLE
airdrop değerli mi?

### ISSUE THREAD

**Issue by IHCMATH** [IBAX-io/go-ibax#1430]
### Clear and concise description of the problem

avax gibi olur mu?
cosmos gibi olur mu?
flux gibi olur mu?

### Suggested solution

bunun için en az onlar kadar işlevsel bir network kurmaları gerekir.

### Alternative

diğer ağlar ile konfigürasyon kurulması gerekecek.

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by IHCMATH** [comment]
diğer ağların eksik noktalarını belirleyip yola çıkmak en mantıklısı.

**Comment by IHCMATH** [comment]
yapılanı yapmak değil yapılmayanı yapmak değer kazandırır.

**Comment by IHCMATH** [comment]
son 2 gün, bakalım ne olacak? nasıl başlarsa öyle gider...

**Comment by uyetkin87** [comment]
Discord tarafı çöp yığını gibi. Ne bekliyorsun?

**Comment by FatihX1X** [comment]
Güzel projeye benziyor ama bakalım zaman gösterecek binance ile ortak gibi duruyolar

**Comment by ysfcndgr** [comment]
Sorunuz bir sorun veya öneri içermiyor. Bu yüzden konuyu kapatıyorum.
