### ISSUE TITLE
Sosyal medya hesapları

### ISSUE THREAD

**Issue by dejavu1445** [IBAX-io/go-ibax#1488]
### Describe the bug

While connecting to your Social Media pages through your site, the "Connect in this way" tab does not appear.

### Reproduction

While connecting to your Social Media pages through your site, the "Connect in this way" tab does not appear.

### System Info

```shell
While connecting to your Social Media pages through your site, the "Connect in this way" tab does not appear.
```

### Logs

```shell
While connecting to your Social Media pages through your site, the "Connect in this way" tab does not appear.
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by atifileri** [comment]
ibax nice

**Comment by ysfcndgr** [comment]
You should support your problems with a more detailed explanation and screenshots.
