### ISSUE TITLE
daha kolay 

### ISSUE THREAD

**Issue by agirkadir** [IBAX-io/go-ibax#1557]
### Describe the bug

daha kolay bir mod olabilir bütün gitevler aramak sorunda kalmayalım

### Reproduction

ibax güzel ve kolay bir hesap olmalı

### System Info

```shell
alternatif sohbet
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by IHCMATH** [comment]
tüm görevlerin içinden yapılmayanları, bekleyen görevler adı altında bir sekmeyle gösterebilirlerdi

**Comment by agirkadir** [comment]
en büyük sorunu bu işte çıkmaz bir yol gibidir
