### ISSUE TITLE
ı relogin my wallet with seed words but change my wallet adress 

### ISSUE THREAD

**Issue by kaan61w** [IBAX-io/go-ibax#1566]
### Describe the bug

I connected with my twitter account and my record was deleted from my account.I don't know how it happened, then I tried logging in again with the recovery words and I entered the account as a result of repeated attempts, albeit difficult. but the wallet address that I registered to airdrop has changedI don't know how it happened, then I tried logging in again with the recovery words and I entered the account as a result of repeated attempts, albeit difficult. but the wallet address that I registered to airdrop has changed

### Reproduction

sddddddddddddddddddddddddI don't know how it happened, then I tried logging in again with the recovery words and I entered the account as a result of repeated attempts, albeit difficult. but the wallet address that I registered to airdrop has changed

### System Info

```shell
I don't know how it happened, then I tried logging in again with the recovery words and I entered the account as a result of repeated attempts, albeit difficult. but the wallet address that I registered to airdrop has changed
```

### Logs

```shell
I don't know how it happened, then I tried logging in again with the recovery words and I entered the account as a result of repeated attempts, albeit difficult. but the wallet address that I registered to airdrop has changed
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Celalktmz** [comment]
Selamlar

**Comment by kaan61w** [comment]
Hıı guys

30 Oca 2022 Paz 20:03 tarihinde Celalktmz ***@***.***> şunu
yazdı:

**Comment by ibaxio** [comment]
This is not possible, so please enter the helper words carefully, including careful punctuation.
