### ISSUE TITLE
Platform altyapı çok kötü

### ISSUE THREAD

**Issue by sokratesGH** [IBAX-io/go-ibax#1580]
### Clear and concise description of the problem

Site arkaplanı derme çatma

### Suggested solution

> code ` arkanplan`

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Sehoo72** [comment]
Testnette olduğunu hala  anlayamadınmi
