### ISSUE TITLE
Biraz karmaşık bir uygulama

### ISSUE THREAD

**Issue by serkancokgezen07** [IBAX-io/go-ibax#1600]
### Clear and concise description of the problem

İBAX proje çok güzel lakin uygulama çok karmaşık ve uygulama değil tam olarak internet bağlantısı olmamalı direk uygulama açılmalı bence ve Türkçe dil seçeneği eklensin

### Suggested solution

Mesela Coinbase borsa uygulaması ve Wexo cüzdan uygulaması çok güzel sizin uygulama çok karmaşık mesela TFB BlacStar uygulaması da tıpkı sizin gibi ama uygulama çok basit anlaşırız ve super sizde bir araştırın derim

### Alternative

TFB BlacStar uygulaması mutlaka inceleyin uygulamanız çok karmaşık ve insanlar Twitter adreslerini bağlamak yerine ekran görüntüsü veya bağlantı atabilir. 

### Additional context

TFB BlacStar uygulasi

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by BadAssKyle** [comment]
Thank you for your support, we will improve it, but Weaver is not for normal users, it is for developers. All users got to know us at a very early stage and are geeks.
