### ISSUE TITLE
Application İBAX!

### ISSUE THREAD

**Issue by Majezikonline** [IBAX-io/go-ibax#1604]
### Clear and concise description of the problem

Application release on Google Play Store and Apple Store as soon as possible.

### Suggested solution

By adding useful information to the application, users can do things that may be useful for IBAX.

### Alternative

Informative videos are added to the IBAX application available on Google Play and Apple Store, and users do something for the benefit of IBAX.

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Koraycan1864** [comment]
Great idea
