### ISSUE TITLE
🌐 Network Selection! 🌐

### ISSUE THREAD

**Issue by Majezikonline** [IBAX-io/go-ibax#1609]
### Clear and concise description of the problem

Most users don't know what Network Selection does when entering the wallet!

### Suggested solution

Hints showing what the network selection does when clicking the (?) sign by adding language supports!

### Alternative

Article referral link explaining the importance of NETWORK SELECTION in wallet entries!

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Koraycan1864** [comment]
Great idea

**Comment by Hanifi06** [comment]
Doğru tespit

**Comment by BadAssKyle** [comment]
Thank you for your kindness suggestion, The problem will be solved after the Mainnet is online, thank you for your attention
