### ISSUE TITLE
daha açıklayıcı olmalı

### ISSUE THREAD

**Issue by beyuzman** [IBAX-io/go-ibax#1614]
### Clear and concise description of the problem

daha açıklayıcı olmalı her şey

### Suggested solution

yazın

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by nescem** [comment]
Telefona kod gelmeli ve böylece yanlışlık olmaz

**Comment by Koraycan1864** [comment]
Great idea
