### ISSUE TITLE
Gösterim 

### ISSUE THREAD

**Issue by Munevver58** [IBAX-io/go-ibax#1660]
### Clear and concise description of the problem

Ana sayfada kullanımına dair görseller veya küçük videolar kullanılmalı.kullamımı daha rahat olur

### Suggested solution

Görseller videolar küçük anektotlar

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ysfcndgr** [comment]
Cüzdanı nasıl oluşturacağınız konusunda bununla ilgili video mevcut. Ne ile alakalı olduğunu yazmamışsınız sorunuz açık değil. Daha detaylı olarak açıklamak isterseniz yeni konu açabilirsiniz. Konuyu kapatıyorum.
