### ISSUE TITLE
IN THIS CASE, WHICH IBAX PARTNER AND PROJECT OWNERS WOULD YOU LIKE TO MAKE A DEAL WITH?

### ISSUE THREAD

**Issue by H-Kandemir** [IBAX-io/go-ibax#1663]
IN THIS CASE, WHICH IBAX PARTNER AND PROJECT OWNERS WOULD YOU LIKE TO MAKE A DEAL WITH?

_Originally posted by @balkes222 in https://github.com/IBAX-io/go-ibax/discussions/1019_

**Comment by Yunusyrr** [comment]
Hala kimse görünmüyor
