### ISSUE TITLE
Wallet Address: 1126-3929-2672-5587-4241

### ISSUE THREAD

**Issue by LoveTh9-cyber** [IBAX-io/go-ibax#1672]
### Describe the bug

"\"{\\\"Account\\\":\\\"1126-3929-2672-5587-4241\\\",\\\"Github\\\":\\\"Lo*****er\\\",\\\"Twitter\\\":\\\"jo*****47\\\"}\""

### Reproduction

"\"{\\\"Account\\\":\\\"1126-3929-2672-5587-4241\\\",\\\"Github\\\":\\\"Lo*****er\\\",\\\"Twitter\\\":\\\"jo*****47\\\"}\""

### System Info

```shell
"\"{\\\"Account\\\":\\\"1126-3929-2672-5587-4241\\\",\\\"Github\\\":\\\"Lo*****er\\\",\\\"Twitter\\\":\\\"jo*****47\\\"}\""
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Sachin14322** [comment]
Ok
