### ISSUE TITLE
Retweet görevi

### ISSUE THREAD

**Issue by Mrt021** [IBAX-io/go-ibax#1703]
### Clear and concise description of the problem

İbax resmi sitesine eklenen son 5000 puanlık retweet görevinde sürekli hata veriyor ve bu herkeste aynı durumda

### Suggested solution

Site trafik sağlayıcısının yükseltilmesi gerekmektedir

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by LeeRAY61** [comment]
In the last 5000-point retweet task added to the Ibax official site, it constantly gives an error and this is the same for everyone.

**Comment by Coskun92** [comment]
Bende de aynı şekilde 5000 puanı alamıyorum.

**Comment by Serhatates7** [comment]
Trafik çok yoğun bu gözüküyor ama bazı hesaplara 5000puan IBAX gönderilmiş geri kalanlar alamamış bunun bir çözüme veya bir açıklamaya kavuşturulması lazım teşekkür ederim

**Comment by ridvanbesli** [comment]
ben son üç görevi yapmama rağmen alamadım

**Comment by turktay** [comment]
bende son 3 görevi yapmıştım ama puanları alamadım yardımcı olur musunuz

**Comment by ysfcndgr** [comment]
Twitter APIsinden kaynaklı olarak son görevler tamamlanılamadı, endişe etmeyin. Son twitter görevleri sıralamaya etki etmeyecek.

**Comment by umutlu17400** [comment]
Bende üç görev var ama hepsi 0 puanı. retweet yaptığımda airdrop sona erdi diyor. gelen giden de yok biz bu airdroptan avcumuzu yaladık galiba
