### ISSUE TITLE
Hata raporu

### ISSUE THREAD

**Issue by Harun1717** [IBAX-io/go-ibax#1708]
### Describe the bug

Son 5000 puanlı twitter görevi başarısız oluyor 

### Reproduction

Yoğunluktan kaynaklı olabilir

### System Info

```shell
Ben sitede yoğunluktan kaynaklı olduğu düşünüyorum
```

### Logs

```shell
İbax
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Abdullahoda** [comment]
ilerleyen saaatlerde verilecektir

**Comment by Serhat67** [comment]
5000 puanlık airdrop neden alınmıyor yogunluk ise neden 6 saat oldu hala alınamadı umarım   bu duzeltilir ve almaya çalışanlar alabilir

**Comment by Sisi06** [comment]
yoğunluktan olduğunu düşünmüyorum,muhtemel bir test aşaması olabilir.

**Comment by ysfcndgr** [comment]
Twitter APIsinden kaynaklı olarak son görevler tamamlanılamadı, endişe etmeyin. Son twitter görevleri sıralamaya etki etmeyecek.
