### ISSUE TITLE
İbax

### ISSUE THREAD

**Issue by 19zeynel92** [IBAX-io/go-ibax#1719]
### Clear and concise description of the problem

İbax istiyorum

### Suggested solution

Herkese dağıtılsın

### Alternative

Bende istiyorum

### Additional context

Sorun yok 

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Abdullahoda** [comment]
gıhuptan puan kazanabılırsın konulara çözüm bul
