### ISSUE TITLE
Tweet

### ISSUE THREAD

**Issue by Harun1717** [IBAX-io/go-ibax#1781]
### Describe the bug

Yeni tweet görevide geçersiz hata veriyor

### Reproduction

İbax

### System Info

```shell
İbax
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jerdal0909** [comment]
Thanks to you, I got scammed. I don't believe you.
I did not get 5000-500-200 retweets points. You are a liar
