### ISSUE TITLE
5000 ve 500 puanlık  görev hata veriyor

### ISSUE THREAD

**Issue by Nesim581** [IBAX-io/go-ibax#1786]
### Describe the bug

Retwet hatası var  görevi yapmamıza rağmen verilmedi puanlar

### Reproduction

Puan hatası

### System Info

```shell
Sistem çok yavaş
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Ufuk145355** [comment]
Retwet hatası var görevi yapmamıza rağmen verilmedi puanlar
