### ISSUE TITLE
***** Enemies Within You  *****  İbaxnetwork 

### ISSUE THREAD

**Issue by Despair016** [IBAX-io/go-ibax#1835]
### Clear and concise description of the problem

![2](https://user-images.githubusercontent.com/97787127/152239496-7e10fd87-03a9-40f5-9ffa-292c5907fc04.jpg)
![photo6041947984293377953](https://user-images.githubusercontent.com/97787127/152239501-e54bf286-6e7d-49c2-b44a-df5fd3993f3f.jpg)
Says Friends, If Distribution Can't Be Provided, take back all RT's and spam the twetter account 

### Suggested solution

Don't Give Rights to the Undeserved  

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by BadAssKyle** [comment]
Can't really understand Turkish. We just finish the airdrop and we are at the liquidation stage will finish liquidation in Q2， please stay with us.

**Comment by BadAssKyle** [comment]
After the liquidation, we will launch our main network and start redeeming IBXC as soon as possible, before we can do so, we must complete the private sale. Please give us some patient and support.
