### ISSUE TITLE
İbax

### ISSUE THREAD

**Issue by tolgauslu1** [IBAX-io/go-ibax#185]
### Describe the bug

İbax New account bug

### Reproduction

İbax

### System Info

```shell
İbax
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ysfcndgr** [comment]
You should describe your problem fully.
