### ISSUE TITLE
Bedava Airdrop

### ISSUE THREAD

**Issue by muhmmedcelik** [IBAX-io/go-ibax#1858]
### Clear and concise description of the problem

https://join.swissborg.com/en/r/muhammFLNS

Üye ol kyc yap 50€ yatır çek biletini ac 100€ kadar hediyeni kap. 

### Suggested solution

Her biletten minimum 2€ çıkıyor. 

### Alternative

Anında yatirip cekebilirsin paranı.

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ysfcndgr** [comment]
Buraya sadece ibax hakkındaki soru ve görüşlerinizi yöneltin. Konuyu kapatıyorum.
