### ISSUE TITLE
Turkish Language

### ISSUE THREAD

**Issue by ceyhannnburak** [IBAX-io/go-ibax#189]
### Clear and concise description of the problem

This is a platform where Turks enter a lot. Turkish support sections are insufficient for us.

### Suggested solution

You should get Turkish moderators and you should provide Turkish language support.

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TheMunay** [comment]
I agree. We want Turkish language support.

**Comment by EminOzaydin** [comment]
I agree. We want Turkish language support.

**Comment by Sergen3535** [comment]
we definitely want

**Comment by Hatemoglu91** [comment]
Kesinlikle istiyoruz

**Comment by ozkankalkan** [comment]
definitely  good idea

**Comment by BadAssKyle** [comment]
Yes I think you are right we are shortage of Turkish support who willing to be our support? We will reward with IBAX points monthly. and we just launched a new Developer campaign for Dev community and User community. People with IBAX points will level up and get Rankings

**Comment by BadAssKyle** [comment]
Please contact @ibaxtr for further details（Become a Turkish Support）
