### ISSUE TITLE
Türkce

### ISSUE THREAD

**Issue by tolgaakkoc43** [IBAX-io/go-ibax#1891]
### Clear and concise description of the problem

Side turkce desteği verecekmi

### Suggested solution

Turkce dil destegi

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ysfcndgr** [comment]
Yakın zamanda türkçe dil desteği sitemize entegre edilecek.

**Comment by mrttgrl** [comment]
> Yakın zamanda türkçe dil desteği sitemize entegre edilecek.

Güzel haber. umarım kısa zamanda entegre olur.

**Comment by Agnostiko** [comment]
Çok iyi olur

**Comment by llllruzgarllll** [comment]
ben ecoliplere giremiyorum yeni bitane acsam ayni şeyler olurmu

**Comment by ysfcndgr** [comment]
Türkçe dil desteği entegre edilmiştir konuyu kapatıyorum
