### ISSUE TITLE
Puanlarım sayfamda neden görünmüyor acaba

### ISSUE THREAD

**Issue by 21rn** [IBAX-io/go-ibax#1899]
### Describe the bug

Puanlarım sayfamda neden görünmüyor acaba
![IMG_20220214_062728](https://user-images.githubusercontent.com/98282921/153804525-71a75474-765c-40c9-ba78-da5e849d9307.jpg)
![IMG_20220214_062806](https://user-images.githubusercontent.com/98282921/153804530-0ccd9770-c9e5-4bb6-92db-89c3fcb55f05.jpg)
![Uploading Screenshot_2022-02-14-06-28-15-343_com.android.chrome.jpg…]()

### Reproduction

![Screenshot_2022-02-14-06-28-43-896_com android chrome](https://user-images.githubusercontent.com/98282921/153804534-0424756d-2f75-4bb3-88cf-06f4a7d68bdd.jpg)
![Screenshot_2022-02-14-06-28-35-293_com android chrome](https://user-images.githubusercontent.com/98282921/153804537-6c52ed3e-ebf6-43db-9583-ef08e0e9abe8.jpg)
![Screenshot_2022-02-14-06-28-26-598_com android chrome](https://user-images.githubusercontent.com/98282921/153804538-d652155b-361d-45c6-8249-7aa01d36a49e.jpg)

### System Info

```shell
Pıanlarım görünmüyor neden acaba
```

### Logs

```shell
Sayfamda puanlarım görünmüyor
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ysfcndgr** [comment]
Redeem tarafından görebilirsiniz, web sitesinde güncellemeler yapıyoruz.
