### ISSUE TITLE
Scammer 15.000 human he cheated on points. points are invalid. altarpiece

### ISSUE THREAD

**Issue by caner550** [IBAX-io/go-ibax#1915]
### Describe the bug

By deceiving 15,000 people. Twitter community redirected. the score given is rubbish github 3 5 said he will distribute it to his own man. first 1000 people should know how to write the remaining 15,000 people were deceived don't trust if you want proof check telegram pages

### Reproduction

Xbax scammer

### System Info

```shell
00010011
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by umit65** [comment]
Proje o kadar büyük ki hiç bitmiyor uzadıkca uzuyor

**Comment by caner550** [comment]
> Proje o kadar büyük ki hiç bitmiyor uzadıkca uzuyor

Balon olduğu için olabilir . Abartı ve scam. 
Kandırarak büyümek dolandırıcılıktir

**Comment by umit65** [comment]
Banada öyle geliyor
