### ISSUE TITLE
İbax Network airdrop ne kadar kazandık

### ISSUE THREAD

**Issue by Githubcem** [IBAX-io/go-ibax#1961]
### Clear and concise description of the problem

http://bc.vc/6lDG6ln

### Suggested solution

http://bc.vc/6lDG6ln

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by umit65** [comment]
ne kazandık

Githubcem ***@***.***>, 11 Mar 2022 Cum, 13:57 tarihinde şunu
yazdı:
