### ISSUE TITLE
Cüzdan

### ISSUE THREAD

**Issue by Azizatli21** [IBAX-io/go-ibax#204]
### Clear and concise description of the problem

Cüzdan oluşturmak çok zor ve zahmetli bunu dağa anlaşılir bir sekilde dizayn edebilir miyiz

### Suggested solution

Metamask takı gibi bir sistem olabilir

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Enee97** [comment]
Gayet mantikli

**Comment by ysfcndgr** [comment]
Şuanki sistem gayet sade ve anlaşılabilirdir.
