### ISSUE TITLE
This snippet of "packages/api/route.go" has a few errors.

### ISSUE THREAD

**Issue by zukenberger** [IBAX-io/go-ibax#2095]
### Describe the bug

I can see a few problems in this code snippet. First, the "nodeStateMiddleware" variable is given as the first parameter to the "api.Use()" function, but this variable is not defined, so its value is unknown. Therefore, the definition of the "nodeStateMiddleware" variable should be added in this code snippet. In addition, the "authRequire()" function is used in the calls to some functions such as "getContractInfoHandler" and "getContractsHandler" in this code snippet, but the function is not specified, so it is not clear what it does. Therefore, the definition of this function should also be added. If you fix these problems, I believe that the errors in this code snippet can be resolved.

### Reproduction

In order to run this snippet properly, it is necessary to define the missing variables and functions. For example, it should be stated what the variable "nodeStateMiddleware" is and what it does. It should also be explained what the "authRequire()" function is and what it does. Once these are done, the errors found in this snippet can be properly resolved. However, if this information is not available, it may not be possible to correct errors.

### System Info

```shell
Browser
```

### Logs

```shell
package api

import (
	"net/http"
	"github.com/IBAX-io/go-ibax/packages/consts"
	"github.com/IBAX-io/go-ibax/packages/service/node"
	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
)

const corsMaxAge = 600

type Router struct {
	main        *mux.Router
	apiVersions map[string]*mux.Router
}

func (r Router) GetAPI() *mux.Router {
	return r.main
}

func (r Router) GetAPIVersion(preffix string) *mux.Router {
	return r.apiVersions[preffix]
}

func (r Router) NewVersion(preffix string) *mux.Router {
	api := r.main.PathPrefix(preffix).Subrouter()
	r.apiVersions[preffix] = api
	return api
}

// Route sets routing pathes
func (m Mode) SetCommonRoutes(r Router) {
	// Undefined variables are defined.
	nodeStateMiddleware := func(next http.Handler) http.Handler {
		// use variable
```

### Validations

- [x] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by scottafk** [comment]
Thanks, The middleware has been declared in 'api/middlewares.go' file.
