### ISSUE TITLE
SAYFADA NELER YAPABİLECEĞİMİZİ ANLATAN BİR VİDEO YADA MAKALE EKLENMELİ

### ISSUE THREAD

**Issue by sedat2855** [IBAX-io/go-ibax#244]
### Clear and concise description of the problem

bu sayfada neler yapabileceğimizi anlatan video eklenebilir

### Suggested solution

açıklayıcı bir video eklenmeli

### Alternative

sayfada neler yapabileceğimizi anlatan bir makale ana sayfaya konulabilir

### Additional context

1

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ysfcndgr** [comment]
Sorunun hangi sayfa için olduğunu belirtmelisiniz ve detaylı açıklama yapmalısınız.
