### ISSUE TITLE
Ana menüde cüzdan bağlantısı olmalı. 

### ISSUE THREAD

**Issue by Egomen47** [IBAX-io/go-ibax#255]
### Clear and concise description of the problem

Maalesef website de ana menüdeki yeni arayüz kafa karıştırıcı. Cüzdana bağlanamıyorum. Ve cüzdan kısmında bir hata var mı emin olamıyorum. Çünkü cüzdan ekleme işlemi çok kafa karıştırıcı ve gereken işlemleri yapıp yapamadığım hususunda şüphelerim var. 

### Suggested solution

Ana menüde cüzdanın aktif olup olmadığını anlayabilmeliyiz. 

### Alternative

Tüm kurulum işlemlerini içeren açıklayıcı ve altyazılı bir YouTube videosu yayınlanmalı. 

### Additional context

Yeni arayüz geçişlerinde problemler de söz konusu. 

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ysfcndgr** [comment]
IBAX arayüzü gayet sade ve anlaşılabilirdir.
