### ISSUE TITLE
Referans 

### ISSUE THREAD

**Issue by Sadi65** [IBAX-io/go-ibax#258]
### Clear and concise description of the problem

Referans istemiyoruz bu konuda yardımcı olabilir misiniz 

### Suggested solution

Sosyal medyalarda paylaşmak duyurmak referans olmadan

### Alternative

Referans olmasa  daha adil olur herkese eşit dağıtılmalı 

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ysfcndgr** [comment]
Mümkün değil.
