### ISSUE TITLE
fake account

### ISSUE THREAD

**Issue by CFarketmez** [IBAX-io/go-ibax#262]
### Clear and concise description of the problem

we have so many fake user account such as the last competition same guy won the competition two time in sale list and that is not good for other users because this show  some correction problem so i cannot trust competition this which have some user correction issue. that link i talking about : https://twitter.com/IbaxNetwork/status/1483348757034975233?s=20 same guy the nurullah aşan i think won two time in same competition.

### Suggested solution

i dont know very well can we check with ip address for solition or at least on twitter someone have to check users who won so every users will have same chance to win. 

### Validations

- [x] Read the [docs](https://docs.ibax.io).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by BadAssKyle** [comment]
We will fix this after the airdrop is over and we will have 2-3 weeks of data checking time to filter this, please trust us and thank you for your support.

**Comment by CFarketmez** [comment]
that answer so clear thanks. we will support you and now i will be more believer thanks.

**Comment by CFarketmez** [comment]
> We will fix this after the airdrop is over and we will have 2-3 weeks of data checking time to filter this, please trust us and thank you for your support.

and another q . it will be on ip addres i mean the checking
