### ISSUE TITLE
hi IBAX TEAM

### ISSUE THREAD

**Issue by ulvidevrim** [IBAX-io/go-ibax#266]
### Clear and concise description of the problem

I can't find anything to say you're doing very well

### Suggested solution

I can't find anything to say you're doing very well

### Alternative

I can't find anything to say you're doing very well

### Additional context

I can't find anything to say you're doing very well

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Enee97** [comment]
Very good
