### ISSUE TITLE
cüzdan anahtarını 

### ISSUE THREAD

**Issue by ulvidevrim** [IBAX-io/go-ibax#267]
### Clear and concise description of the problem

cüzdan anahtarını kaybetmiş kişiler var

### Suggested solution

bunlar için ne yapılabilinir

### Alternative

yeni hesap mı 

### Additional context

açmaları gerek

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ysfcndgr** [comment]
Bu konuda yapabileceğimiz herhangi bir şey yok.
