### ISSUE TITLE
I'm sure your project will grow a lot, I wish you success in your work.

### ISSUE THREAD

**Issue by s4155643** [IBAX-io/go-ibax#269]
### Describe the bug

I'm sure your project will grow a lot, I wish you success in your work.

### Reproduction

the system is a project with a very wide audience, your success is very close.

### System Info

```shell
the system is a project with a very wide audience, your success is very close.
```

### Logs

```shell
It's like the system's logo is written in very charismatic words.
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by BadAssKyle** [comment]
Sorry I have to close this
