### ISSUE TITLE
Проблеме с кошельками

### ISSUE THREAD

**Issue by Snyperss** [IBAX-io/go-ibax#281]
### Describe the bug

Вовремя  регистрации у некоторых пользователей не возможно войди в свои кошельки.

### Reproduction

Weaver.ibax

### System Info

```shell
Система на сайте weaver ibax.io
```

### Logs

```shell
Ошибка при регистрации
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ysfcndgr** [comment]
Describe your problem fully. What error are you encountering?
