### ISSUE TITLE
У этого проекта есть будущее

### ISSUE THREAD

**Issue by Snyperss** [IBAX-io/go-ibax#282]
### Clear and concise description of the problem

Красивые проект

### Suggested solution

Многие люди довольны 

### Alternative

.

### Additional context

Есть возможность заработать на этом проекте

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ysfcndgr** [comment]
Thank you but, this is not a problem.
