### ISSUE TITLE
ıbax mobil cüzdanı gelecekmi 

### ISSUE THREAD

**Issue by BAHA7808** [IBAX-io/go-ibax#296]
### Clear and concise description of the problem

ıbax mobil cüzdanı gelecekmi 

### Suggested solution

böyle büyük bir proje için beklemek en zor olanı

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Astenov** [comment]
Öyle bir söylenti duydum ama kesinlik yok

**Comment by Ffurkansutcu** [comment]
Kesinlikle olmalı

**Comment by Halo0642** [comment]
Cüzdan gelmeli , zira bu platform bana çok karisik geliyor

**Comment by 2558Mete** [comment]
Önemli bir konu👍

**Comment by ysfcndgr** [comment]
Gerekli açıklamayı IBAX ekibi yapacaktır.
