### ISSUE TITLE
Türkçe dil desteği

### ISSUE THREAD

**Issue by Majezikonline** [IBAX-io/go-ibax#332]
### Clear and concise description of the problem

Forum içeriklerinin tamamen ingilizce olması bizi çok fazla zorluyor. Site içerisindeki arayüzünün Türkçe olması gibi bir öneride bulunalım! 

### Suggested solution

Türkçe dil desteği

### Alternative

Uygulama içerisine entegre edilmiş dil çevirici bot.

### Additional context

Destek kısmında Türkçe desteğin olması.

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Aliprl** [comment]
Türkçe dil desteği ilerliyen zamanlarda gelmeli aynen

**Comment by Ruhulbeyan** [comment]
Saygı değer IBAX yöneticilerine lutfen türkçe dil destegini getirin arkadaş güzel bir konuya değinmiş katılıyorum

**Comment by atifileri** [comment]
Bencede gelmeli

**Comment by ysfcndgr** [comment]
Türkçe dil desteği hazırlanıyor yakın zamanda sitemize entegrasyon gerçekleşecek.
