### ISSUE TITLE
İbax dont standart.

### ISSUE THREAD

**Issue by Azoahai** [IBAX-io/go-ibax#345]
### Clear and concise description of the problem

1 hAw€ !baX ₺aRz me₺aW€R$€. ✓

### Suggested solution

We waiting 😜

### Alternative

Wait

### Additional context

Time and wait

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Yusuf56418** [comment]
Katılıyorum
