### ISSUE TITLE
ibax puanları ne oluyor neye yarıyor?

### ISSUE THREAD

**Issue by akinx30** [IBAX-io/go-ibax#349]
### Describe the bug

ibax puanları nedir ?

### Reproduction

?

### System Info

```shell
?
```

### Logs

```shell
?
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CFarketmez** [comment]
puanlar toplanacak puanlara göre sıralamalar olacak ona göre ve yaptığımız etkinliklere göre punalar birikecek en sonunda puanlara göre dağıtım olacak puanı çok olanlara daha çok olmak üzere dağıtım olacak https://ibax.io/user/airdrop-rules şurayı türkçeye programla çevirttirirsen gelme şekilleri yazıyor.

**Comment by 2558Mete** [comment]
Eyvallah

**Comment by ysfcndgr** [comment]
IBAX puanları airdroba katılmanız ve ibax coin almanıza yardımcı olacak puanlardır.
