### ISSUE TITLE
Telegram and discord points problem

### ISSUE THREAD

**Issue by Funscos** [IBAX-io/go-ibax#350]
### Describe the bug

I didn't get any points even though I joined your telegram and discord groups
I think there is an issue with that
I saw that other users could not earn points in Telegram groups.
Authorities Can you help with this problem? 
Thank you 🙏

### Reproduction

I didn't get any points even though I joined your telegram and discord groups
I think there is an issue with that
I saw that other users could not earn points in Telegram groups.
Authorities Can you help with this problem? 
Thank you 🙏

### System Info

```shell
Ibax
```

### Logs

```shell
Ibax
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Yenal4526** [comment]
Me too

**Comment by BadAssKyle** [comment]
It's ok no one has it yet
