### ISSUE TITLE
This website have to have link for withdraw our points to our wallets

### ISSUE THREAD

**Issue by HasanKutluayCil** [IBAX-io/go-ibax#354]
### Clear and concise description of the problem

This website have to have link for withdraw our points to our wallets

### Suggested solution

This website have to have link for withdraw our points to our wallets

### Alternative

This website have to have link for withdraw our points to our wallets

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by semihmehmetk** [comment]
nice

**Comment by Nesim581** [comment]
Cüzdan

**Comment by Nesim581** [comment]
Katılıyorum bu görüşüne

**Comment by Yusuf56418** [comment]
Katıldım

**Comment by Egemeneaglee** [comment]
Katılıyorum
