### ISSUE TITLE
Wallet Problem

### ISSUE THREAD

**Issue by furkangencer4** [IBAX-io/go-ibax#36]
### Describe the bug

Hello, when we register the platform via Twitter and create wallet, we generate a key called account seed and we have a wallet id.
Here is the problem, Most of the crypto wallets we do the same and the key we generate is seed in case we loose our wallet or we use it to import somewhere else. At the first stage i thought its my seed but it was not. i supposed to open the platform and find back up section to get my private key. Many users had the same issue. Now i can not log in my wallet. 
I was suggested i can create another one, but my account is linked with that wallet, so i cant create another wallet for my twitter.
There is misinformation during wallet creation process, why we generate a seed and it doesn't work anywhere? It would be better if we generate our actual account seed during the wallet creation process otherwise we wont be able to access our wallet as i cant now.

![image](https://user-images.githubusercontent.com/97418613/148853125-617ca8e1-2ae3-423a-9386-a99e55797814.png)

thanks

### Reproduction

![image](https://user-images.githubusercontent.com/97418613/148853125-617ca8e1-2ae3-423a-9386-a99e55797814.png)

### System Info

```shell
wallet
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by furkangencer4** [comment]
i also got this screen when i try to connect wallet
![image](https://user-images.githubusercontent.com/97418613/148854128-abeb32af-309e-4f4f-966f-0aa6d425278b.png)

**Comment by Olumeni1** [comment]
Inbox her she will not inbox you first

@Mitchells1 

$35 - $500+ discount on the first 10 person's
https://t.me/bitcoinpartyy
https://t.me/bitcoinpartyy

**Comment by Olumeni1** [comment]
Get help on all issues

Inbox her she will not inbox you first

@Mitchells1 

$35 - $500+ discount on the first 10 person's
https://t.me/bitcoinpartyy
https://t.me/bitcoinpartyy

**Comment by eldogan** [comment]
I did all the operations and got 12500 points
but i can't create wallet
your page is not working
please intervene

**Comment by eldogan** [comment]
I did all the operations and got 12500 points
but i can't create wallet
your page is not working
please [intervene](url)

![resim_2022-01-14_153539](https://user-images.githubusercontent.com/97596894/149516371-1211dca9-b8ec-4c14-b32b-567aaafc5d3e.png)

![ibax 1](https://user-images.githubusercontent.com/97596894/149516387-fbe77ade-fdc2-471c-a4e5-f27f7617dcb2.png)

![ibax 2](https://user-images.githubusercontent.com/97596894/149516396-971621bb-16e0-48df-a9c0-2281cd304a71.png)

**Comment by furkangencer4** [comment]
> I did all the operations and got 12500 points but i can't create wallet your page is not working please [intervene](url)
> 
> ![resim_2022-01-14_153539](https://user-images.githubusercontent.com/97596894/149516371-1211dca9-b8ec-4c14-b32b-567aaafc5d3e.png)
> 
> ![ibax 1](https://user-images.githubusercontent.com/97596894/149516387-fbe77ade-fdc2-471c-a4e5-f27f7617dcb2.png)
> 
> ![ibax 2](https://user-images.githubusercontent.com/97596894/149516396-971621bb-16e0-48df-a9c0-2281cd304a71.png)

its obvious the team doesn't care at all, i opened 2 different topic for that and explained detail what is the problem.
The response was i can open account with new twitter, they don't even attempt to solve it.
Anyway i found myself how to fix it, you can reach me on telegram i will show you @furkangncr

**Comment by eldogan** [comment]
thank you @furkangncr,
Ibax admins please thanks @furkangncr because he works for you...

**Comment by Olumeni1** [comment]
https://t.me/bitcoinpartyy
Join telegram and report to the admin for
assistance👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇

https://t.me/bitcoinpartyy

**Comment by Olumeni1** [comment]
https://t.me/bitcoinpartyy
https://t.me/bitcoinpartyy

Join the group and inbox the admin 👇👇👇👇👇👇👇👇👇

https://t.me/bitcoinpartyy
https://t.me/bitcoinpartyy

**Comment by omerboyarlar** [comment]
I did what is done in the video on your page to create a wallet. but on the telegram page it says we need to save the private key. but I can't login again. Will all my work and references be lost? What can I do.
(I saved the keywords but it doesn't work)

**Comment by bugraozyurt** [comment]
Same.

**Comment by BadAssKyle** [comment]
> ### Describe the bug
> Hello, when we register the platform via Twitter and create wallet, we generate a key called account seed and we have a wallet id. Here is the problem, Most of the crypto wallets we do the same and the key we generate is seed in case we loose our wallet or we use it to import somewhere else. At the first stage i thought its my seed but it was not. i supposed to open the platform and find back up section to get my private key. Many users had the same issue. Now i can not log in my wallet. I was suggested i can create another one, but my account is linked with that wallet, so i cant create another wallet for my twitter. There is misinformation during wallet creation process, why we generate a seed and it doesn't work anywhere? It would be better if we generate our actual account seed during the wallet creation process otherwise we wont be able to access our wallet as i cant now.
> 
> ![image](https://user-images.githubusercontent.com/97418613/148853125-617ca8e1-2ae3-423a-9386-a99e55797814.png)
> 
> thanks
> 
> ### Reproduction
> ![image](https://user-images.githubusercontent.com/97418613/148853125-617ca8e1-2ae3-423a-9386-a99e55797814.png)
> 
> ### System Info
> ```shell
> wallet
> ```
> 
> ### Logs
> _No response_
> 
> ### Validations
> * [x]  Read the [docs](https://docs.ibax.io).
> * [x]  Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
> * [x]  The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

Please check this URL
https://github.com/IBAX-io/go-ibax/discussions/62

**Comment by BadAssKyle** [comment]
> ### Describe the bug
> Hello, when we register the platform via Twitter and create wallet, we generate a key called account seed and we have a wallet id. Here is the problem, Most of the crypto wallets we do the same and the key we generate is seed in case we loose our wallet or we use it to import somewhere else. At the first stage i thought its my seed but it was not. i supposed to open the platform and find back up section to get my private key. Many users had the same issue. Now i can not log in my wallet. I was suggested i can create another one, but my account is linked with that wallet, so i cant create another wallet for my twitter. There is misinformation during wallet creation process, why we generate a seed and it doesn't work anywhere? It would be better if we generate our actual account seed during the wallet creation process otherwise we wont be able to access our wallet as i cant now.
> 
> ![image](https://user-images.githubusercontent.com/97418613/148853125-617ca8e1-2ae3-423a-9386-a99e55797814.png)
> 
> thanks
> 
> ### Reproduction
> ![image](https://user-images.githubusercontent.com/97418613/148853125-617ca8e1-2ae3-423a-9386-a99e55797814.png)
> 
> ### System Info
> ```shell
> wallet
> ```
> 
> ### Logs
> _No response_
> 
> ### Validations
> * [x]  Read the [docs](https://docs.ibax.io).
> * [x]  Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
> * [x]  The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

[https://user-images.githubusercontent.com/51123970/149915791-f52f90be-9699-4f3f-8609-25698796b6b1.png](url)

The password is used to encrypt your private key and allow easy access to your account
IBAX does not store your private key, so the private key associated with the password will be stored in your browser's cookie.
When you clear the cookie or use a new browser to access your IBAX account, you will need to import your helper notes and encrypt them again with your password
Of course, you can also regenerate an IBAX account and re-encrypt it with a password

hint：
Take care of your private key (account seed)
Take care of your public key
Take care of your password
Take care of your wallet address

**Comment by Ozgurtolga** [comment]
Wallet hatasını bende alıyorum erişim sağlıyamıyorum lütfen çözünüz anahtar hatası alıyorum

**Comment by Ozgurtolga** [comment]
I'm wallet getting a key error too please find a solution to this problem

**Comment by Vjdt5** [comment]
Bu cüzdan olayına bir çözüm bulunmalı.

**Comment by bugraozyurt** [comment]
Wallet'a bağlanmak için 12 kelimelinizi yeni cüzdan oluşturma kısmına girin (yeni hesap açıyormuş gibi) böylelikle bağlanabilirsiniz. Sonrasında weaver platformundan Private Key'inizi kopyaladıktan sonra tekrar giriş yapabilirsiniz normal şekilde.
-------- Orijinal mesaj --------Kimden: Vjdt5 ***@***.***> Tarih: 24.01.2022  11:51  (GMT+03:00) Alıcı: IBAX-io/go-ibax ***@***.***> Cc: bugraozyurt ***@***.***>, Comment ***@***.***> Konu: Re: [IBAX-io/go-ibax] Wallet Problem (Issue #36) 

Bu cüzdan olayına bir çözüm bulunmalı.

**Comment by Ozgurtolga** [comment]
İlgi ve alakanız için teşekkür ederim problem çözüldü

24 Oca 2022 Pzt 11:53 tarihinde bugraozyurt ***@***.***> şunu
yazdı:

**Comment by bugraozyurt** [comment]
Rica ederim hocam. weaver.ibax.io 'ya girip sağ üstten yanlış hatırlamıyorsam account kısmına girip private keyinizi alabilirsiniz. Private key ile normal girişi sağlayabiliyoruz
-------- Orijinal mesaj --------Kimden: Ozgurtolga ***@***.***> Tarih: 24.01.2022  12:31  (GMT+03:00) Alıcı: IBAX-io/go-ibax ***@***.***> Cc: bugraozyurt ***@***.***>, Comment ***@***.***> Konu: Re: [IBAX-io/go-ibax] Wallet Problem (Issue #36) 

İlgi ve alakanız için teşekkür ederim problem çözüldü



24 Oca 2022 Pzt 11:53 tarihinde bugraozyurt ***@***.***> şunu

yazdı:

**Comment by 2558Mete** [comment]
Teşekkürler

**Comment by Vjdt5** [comment]
İbax private key nereden ulaşabilirim

25 Oca 2022 Sal 02:16 tarihinde 2558Mete ***@***.***> şunu
yazdı:

**Comment by Efsane4167** [comment]
Hersey guzel olcak insallah bu ibaxdan yuzumuz guler

**Comment by Vjdt5** [comment]
cüzdana girebiliyorum ama private key nerede onu bulamadım

27 Oca 2022 Per 01:32 tarihinde Efsane4167 ***@***.***> şunu
yazdı:

**Comment by Dumrul1** [comment]
> Ona gelen kutusu, önce sana gelen kutusu olmayacak
> 
> @MitchellS1
> 
> İlk 10 kişinin [https://t.me/bitcoinpartyy ](https://t.me/bitcoinpartyy) [https://t.me/bitcoinpartyy'de 35$ - 500$+ indirim](https://t.me/bitcoinpartyy)

**Comment by Dumrul1** [comment]
Niye birden fazla cüzdan oluş tulma imkanı sunuyor tek cüzdan yeterli

**Comment by Pharez4G** [comment]
What a great thread

**Comment by Pharez4G** [comment]
I didn’t know about this before now

**Comment by Shamspark** [comment]
> ### Describe the bug
> Hello, when we register the platform via Twitter and create wallet, we generate a key called account seed and we have a wallet id. Here is the problem, Most of the crypto wallets we do the same and the key we generate is seed in case we loose our wallet or we use it to import somewhere else. At the first stage i thought its my seed but it was not. i supposed to open the platform and find back up section to get my private key. Many users had the same issue. Now i can not log in my wallet. I was suggested i can create another one, but my account is linked with that wallet, so i cant create another wallet for my twitter. There is misinformation during wallet creation process, why we generate a seed and it doesn't work anywhere? It would be better if we generate our actual account seed during the wallet creation process otherwise we wont be able to access our wallet as i cant now.
> 
> ![image](https://user-images.githubusercontent.com/97418613/148853125-617ca8e1-2ae3-423a-9386-a99e55797814.png)
> 
> thanks
> 
> ### Reproduction
> ![image](https://user-images.githubusercontent.com/97418613/148853125-617ca8e1-2ae3-423a-9386-a99e55797814.png)
> 
> ### System Info
> ```shell
> wallet
> ```
> 
> ### Logs
> _No response_
> 
> ### Validations
> * [x]  Read the [docs](https://docs.ibax.io).
> * [x]  Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
> * [x]  The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

Hello

**Comment by Shamspark** [comment]
Hi

**Comment by Koraycan1864** [comment]
Great idea

**Comment by tajnia** [comment]
hi 
i setup  go-ibax  and then  run
go-ibax start

What should have happened after that?

**Comment by tajnia** [comment]
go-ibax start  :

time="2022-02-02T18:09:09Z" level=info msg="Loading config" path=data/config.toml
time="2022-02-02T18:09:09Z" level=info msg="started with" version="1.3.0 branch.unknown commit.unknown time.unknown" work_dir=data
time="2022-02-02T18:09:09Z" level=info msg="Node running mode" fields.time="2022-02-02T18:09:09Z" file=mode_fabrics.go func=modes.logMode line=211 loader=blockchain_daemon_loader mode="Public blockchain"

and nothing
