### ISSUE TITLE
Cuzdan baglama

### ISSUE THREAD

**Issue by Efsane4167** [IBAX-io/go-ibax#363]
### Describe the bug

Cuzdani bağlayamiyorum.ekran oylece kaliyor.cuzdanima girmiyor.ve  beyaz ekran kaliyor.  Youtube kanaliniz var ama kanalinizda  cuzdan baglama nasil yapilir detayli anlatim videosu atin lutfen.

### Reproduction

Cuzdan baglama yaparken 3 tane ag cikiyor.cuzdanimada giremiyorum.

### System Info

```shell
Cuzdana girerken beyaz ekranda kaliyo
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Yusuf56418** [comment]
Katılıyorum

**Comment by amrothelanesse** [comment]
Cuzdani nereye bagliyoruz

**Comment by Efsane4167** [comment]
Cok sukur duzeldi .aslinda youtuberler bile dogrundurust anlatamiyor

**Comment by Berking0** [comment]
sayfanın dil seçeneğini değiştirmişsinizdir yada geçmişi silmenizde ayrıca yardımcı olabilir.

**Comment by Sercan5959** [comment]
Cuzdani bağladim giris yapamiyorum 15 anahtar kelime var gecersiz diyor

**Comment by Sercan5959** [comment]
Yardim edermisiniz
