### ISSUE TITLE
Tam olarak ne zaman coin olacak

### ISSUE THREAD

**Issue by Yusuf56418** [IBAX-io/go-ibax#372]
### Describe the bug

Borsalara coin olarak düşecek mi

### Reproduction

Tam olarak ne zaman düşer

### System Info

```shell
System
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by iiiiiiiiiii546** [comment]
beklemedeyiz

**Comment by emryldz86** [comment]
Umarım güzel coin verirler 😀

**Comment by Davut4** [comment]
Beklıyoruz

**Comment by Hsnyldzc1991** [comment]
Nasip

**Comment by emryldz86** [comment]
Ne zaman dağıtım yapılacak bilgisi olan var mı arkadaşlar
