### ISSUE TITLE
Topladoğımız puanlar  nerede

### ISSUE THREAD

**Issue by Nesim581** [IBAX-io/go-ibax#373]
### Clear and concise description of the problem

Çözüm odaklı

### Suggested solution

Hızlı ve güvenilir yollar bulmak

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Memo4949** [comment]
Sağdaki 3 noktaya tıklayıp cüzdana gidin ve tekrar ordan profil sekmesine dokunduğunuz zaman puanlarınız gözükücek

**Comment by emryldz86** [comment]
Veya dili ingilizceye çevirdiğinizde görünüyor

**Comment by Halo0642** [comment]
Ben bulamadım bir türlü

**Comment by BadAssKyle** [comment]
Please check it again，if you have further issue please print a screen or make a video for your problem

**Comment by Nurlan986** [comment]
Ana saufanızda bula bilorsiniz

**Comment by Usermisafir** [comment]
Ana sayfada birşey yazmıyor sadece topladığımız puanlar var bugün ref. Yaptım 5 ibxc  geldi
