### ISSUE TITLE
0'm-Y g0T

### ISSUE THREAD

**Issue by Azoahai** [IBAX-io/go-ibax#376]
### Clear and concise description of the problem

Everything is very clear and useful for ibax, dear administrators. we can't find fault. Can you give me a clue 🤔🤔🥁

### Suggested solution

Yes i listening sir😶

### Alternative

Eeee

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by BadAssKyle** [comment]
Thank you for your support.
