### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Voltrader23** [IBAX-io/go-ibax#408]
### Describe the bug

As you know, we earn IBAX points as we complete daily retweet tasks. However, some users including me get an error even if complete the retweet tasks properly. which is 'Please retweet the post then get your IBAX points'. I am sure I logged in with correct account. I am using chrome and it's uptaded
![tweet](https://user-images.githubusercontent.com/98291457/150705093-e85fbc5f-3a07-4c14-abd6-7c74bdb10b71.PNG)
![ss](https://user-images.githubusercontent.com/98291457/150705096-6ff3b7ea-0552-4ff4-9b6c-07013e145aff.PNG)
.

### Reproduction

<p class="el-message__content">Please try again later</p>

### System Info

```shell
Device name:ZED_AIR_CX3
Processor:Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz   2.00 GHz
Ram: 8gb
System type: 64bit
Edition: Windos 10 Home
Browser: Chrome lastest version
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by BadAssKyle** [comment]
normally this kind of issue is because we are getting heavy traffic， you can unretweet this task and then get back later and do it again. Twitter have a limit API to allow us check the post stats so it could causing this problem. It's Twitter's limitation cause this problem.
