### ISSUE TITLE
IBAX cüzdan bulma

### ISSUE THREAD

**Issue by ahmetx12** [IBAX-io/go-ibax#479]
### Describe the bug

İBAX cüzdanını bulmak istiyorsanız kesinlikle kayıt olurken kelimelerinizi saklamanız gerekiyor ayrıca cüzdanı açtıktan sonra share kısmına basarak ordaki private key bölümünüde saklamanız gerekiyor bunlar ilerde kesinlikle lazım olucak üşenmeden bir kağıda yazın saklayın en kötü bilgisayarda saklayın

### Reproduction

ibax resmen cüzdan bölümünü saklamış bulunmuyor

### System Info

```shell
sistem
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Turbolaz61** [comment]
Sadece cüzdan adresini yazmakta olur

**Comment by Oguzhanhalil52** [comment]
Cüzdan kelimelerim doğru olmasina ragmen cuzdana giriş yapamiyorum baska türlü giriş yapabilme sansim var mi uygulamaya giriyorum fakat cuzdana ulasamiyorum ya da yeni cuzdan acip hesabima baglayabilie miyim
