### ISSUE TITLE
Wallet linking given code issue

### ISSUE THREAD

**Issue by Cemalcanyildiz** [IBAX-io/go-ibax#568]
### Describe the bug

Hello, when we register to the platform via Twitter and create a wallet, we generate a key called the account seed and we have a wallet ID. The problem is that we do the same with most crypto wallets and the key seed we generate in case we lose our wallet or use it to import it elsewhere
At first I thought it was my seed but it wasn't. To get my private key, I had to open the platform and find the backup partition. Many users had the same problem. Now I can't login to my wallet.
It has been suggested that I can create another one, but my account is linked to that wallet so I cannot create another wallet for my twitter.
 It would be better if we generate our real account seed during the wallet creation process otherwise we will not be able to access our wallet as I cannot do it now.
Big problem for me and for novice people like me

### Reproduction

...

### System Info

```shell
....
```

### Logs

```shell
....
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Halo0642** [comment]
Bende bu konudan müzdaribim.bende hatırlamıyorum kodlarımı,yenisini de açamıyorum.mutlak bı çözüm gerekli bu konu da yoksa epey kişi zarar görecek 😔
