### ISSUE TITLE
Puan

### ISSUE THREAD

**Issue by turgaycenberlitas** [IBAX-io/go-ibax#57]
### Describe the bug

![20220117_203007](https://user-images.githubusercontent.com/97908395/149815914-d122a778-19b2-42f3-9dee-7b4af2c6f78e.jpg)

Puan üst tarafta neden görün müyor?  Yardımcı olur musunuz?

### Reproduction

![20220117_203007](https://user-images.githubusercontent.com/97908395/149816273-9cd14727-e49e-4ae1-883b-4761f941315b.jpg)

Puan üst tarafta neden görün müyor?

### System Info

```shell
Puan üst tarafta neden görün müyor?
```

### Logs

```shell
Puan üst tarafta neden görün müyor?
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hrhrrcp** [comment]
İngilizce yap yakışıklı

**Comment by Ruhulbeyan** [comment]
Arkadaşlar bu sisteme guvenim tam teşekkür ederim

**Comment by Majezikonline** [comment]
Umarım sistem yamuk yapmaz😄

**Comment by Turbolaz61** [comment]
Ula çıkarımız olmasa kodum ıbaxının amna ama para var işin ucunda
