### ISSUE TITLE
Çeviri yapıldığında puanların görünmemesi hatası

### ISSUE THREAD

**Issue by Ysnfb** [IBAX-io/go-ibax#58]
### Describe the bug

![1](https://user-images.githubusercontent.com/96961102/149836863-7ac3e4be-f468-4f5f-a570-e0df23c87af6.jpeg)

![2](https://user-images.githubusercontent.com/96961102/149837048-4e2f1405-e680-4008-ad54-2e054bad6bb5.jpeg)

IBAX resmi sitesindeki Sayfa dili Türkçe'ye çevrildiğinde herkesin puanı sıfır(0) olarak görünüyor ama sayfa dili İngilizce olduğunda herkesin almış olduğu puan tam görünüyor.Test aşamasında bu tür küçük sorunların giderileceğini umuyorum.

### Reproduction

IBAX resmi sitesindeki Sayfa dili Türkçe'ye çevrildiğinde herkesin puanı sıfır(0) olarak görünüyor ama sayfa dili İngilizce olduğunda herkesin almış olduğu puan tam görünüyor.Test aşamasında bu tür küçük sorunların giderileceğini umuyorum.

### System Info

```shell
IBAX resmi sitesindeki Sayfa dili Türkçe'ye çevrildiğinde herkesin puanı sıfır(0) olarak görünüyor ama sayfa dili İngilizce olduğunda herkesin almış olduğu puan tam görünüyor.Test aşamasında bu tür küçük sorunların giderileceğini umuyorum.
```

### Logs

```shell
IBAX resmi sitesindeki Sayfa dili Türkçe'ye çevrildiğinde herkesin puanı sıfır(0) olarak görünüyor ama sayfa dili İngilizce olduğunda herkesin almış olduğu puan tam görünüyor.Test aşamasında bu tür küçük sorunların giderileceğini umuyorum.
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Yusufknk** [comment]
Merhaba, Ekipler Projenin (Türkçe dahil) farklı dil versiyonu üzerinde çalışıyorlar.

**Comment by BadAssKyle** [comment]
> Merhaba, Ekipler Projenin (Türkçe dahil) farklı dil versiyonu üzerinde çalışıyorlar.

That's right
