### ISSUE TITLE
ibax puanlar görünmüyor sebebi nedir?

### ISSUE THREAD

**Issue by candmnn** [IBAX-io/go-ibax#661]
### Describe the bug

ibax puanlar görünmüyor sebebi nedir?

### Reproduction

ibax puanlar görünmüyor sebebi nedir?

### System Info

```shell
ibax puanlar görünmüyor sebebi nedir?
```

### Logs

```shell
ibax puanlar görünmüyor sebebi nedir?
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by serkanyigiit** [comment]
Twitter bağlantınız kopmuş olabilir

**Comment by Erden76** [comment]
Sayfayı yenileyip tekrar deneyin

**Comment by Ang0210** [comment]
Great
