### ISSUE TITLE
ibax.io sayfasında aşağı kaydırma çubuğu çalışmıyor.

### ISSUE THREAD

**Issue by emiribax** [IBAX-io/go-ibax#664]
### Describe the bug

ibax.io ana sayfasında aşağı doğru kaydırma çubuğu çalışmıyor. Bundan dolayı sürekli tuş kullanmak zorunda kalıyoruz. Buna bir çözüm istiyoruz.

### Reproduction

https://ibax.io/user/commits

### System Info

```shell
https://ibax.io/user/commits
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Ozgurruhh06** [comment]
Mobil üzerinden girişlerde ara sırada ibx puanları 0 görünüyor ve sayfayı yeniledikçe tekrar eski puanlarım görünüyor

**Comment by ibaxio** [comment]
Try again.
