### ISSUE TITLE
MOBİL UYGULAMA OLACAK MI?

### ISSUE THREAD

**Issue by mamilincoln** [IBAX-io/go-ibax#682]
### Clear and concise description of the problem

İbaxımıza ait mobil uygulama ne zaman çıkar

### Suggested solution

mobil uygulama dahada kolaylaştıracak işimizi

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mucahitbilge** [comment]
En yakin zamanda cikartilmasi gerekiyor cuzdan baglantisinin iyilestirilmesi gerekirse weaver  cuzdaninin metamask gibi bir formata donusturulmesi gerekiyor

**Comment by fdieks** [comment]
İbax kendi cüzdanı olduğu için bir uygulama da kesin çıkacaktır.

**Comment by fusunsnr** [comment]
uygulama olsa daha iyi olur

**Comment by cryptopus58** [comment]
Yakın zamanda geleceğini umuyorum

**Comment by ibaxio** [comment]
Lütfen bu tartışmaya bakın: #629

Please refer to this discussion:  #629
