### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Deadeyetr46** [IBAX-io/go-ibax#705]
### Describe the bug

Wallet problem

### Reproduction

wallet

### System Info

```shell
system
```

### Logs

```shell
run
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by halildemirellx** [comment]
bence cüzdan sadece telefondan girilebilen bir uygulama olsa dahamı yararlı olurdu?

**Comment by ibaxio** [comment]
If you find any bugs, please describe the specific situation.

**Comment by ibaxio** [comment]
> bence cüzdan sadece telefondan girilebilen bir uygulama olsa dahamı yararlı olurdu?

Please submit your suggestions on Ideas of Discussion -  https://github.com/IBAX-io/go-ibax/discussions/categories/ideas
