### ISSUE TITLE
E mail and sms verification

### ISSUE THREAD

**Issue by hes91** [IBAX-io/go-ibax#725]
### Clear and concise description of the problem

In order to prevent wallet losses, e-mail and sms verification feature should come. So people feel more secure

### Suggested solution

For this, kyc verification must come first. It is important that real people take action. This is the only way to get in front of bot accounts. Then people feel more secure via e-mail and sms. They have no fear of losing their recovery codes. If you take this suggestion into consideration, it will be very nice for people.

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ibaxio** [comment]
**IBAX Network is a blockchain project.**

The password is used to encrypt your private key and allow easy access to your account.
**IBAX does not store your private key**, so the private key associated with the password will be stored in your browser's cookie.

When you clear the cookie or use a new browser to access your IBAX account, you will need to import your helper notes and encrypt them again with your password.

Of course you can also regenerate an IBAX account and re-encrypt it with a password.

hint：

- Take care of your private key (account seed)
- Take care of your public key
- Take care of your password
- Take care of your wallet address

**Comment by hes91** [comment]
Thanks good luck
