### ISSUE TITLE
ibax

### ISSUE THREAD

**Issue by Tunc37** [IBAX-io/go-ibax#75]
### Describe the bug

ı love you ıbaxxxx

### Reproduction

ı love you ıbaxxxx

### System Info

```shell
ı love you ıbaxxxx
```

### Logs

```shell
ı love you ıbaxxxx
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Tunc37** [comment]
ı love you ıbaxxxx

**Comment by Tunc37** [comment]
ı love you ıbaxxxx

**Comment by Turbolaz61** [comment]
Tunç hesabına 1milyon ıbox gönderildi 😂😂

**Comment by usebaba** [comment]
seni seviyorum ıbaxxxx

**Comment by ysfcndgr** [comment]
Lütfen burayı gereksiz meşgul etmeyin. Konunuz bir sorun içermiyor.
