### ISSUE TITLE
Retweet ödülü

### ISSUE THREAD

**Issue by Sonersasmaz** [IBAX-io/go-ibax#76]
### Describe the bug

Retweet ödülü yeni güncelleme ile gelmemeye başladı

### Reproduction

.

### System Info

```shell
.
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by BadAssKyle** [comment]
Due to the 2 million limit of the Twitter API each month (retweet tasks need to be consumed 5 times at a time) we have 80,000 people and 5 retweet tasks have hit the API limit, so some users can't get points anymore.
