### ISSUE TITLE
Retweed

### ISSUE THREAD

**Issue by hayat09909** [IBAX-io/go-ibax#77]
### Describe the bug

Bı paylasimi reetwed  yaptığımızda  geri dönüp tamamlandi ya basınca bazen onaylandı yazısı çikmiyor sürekli bekliyoruz

### Reproduction

Reetwed

### System Info

```shell
Reetwed
```

### Logs

```shell
Reetwed
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Majezikonline** [comment]
Türkçe dil desteği lütfen♥️

**Comment by Majezikonline** [comment]
Neden Türkçe dil desteğiniz yok

**Comment by Vernacular30** [comment]
Retweetin onaylanmaması browser den kaynaklı, Chrome ya da benzeri arayüze sahip browser kullanma, ben Operaya geçtim, sorunsuz çalışıyor.

**Comment by ysfcndgr** [comment]
Kullandığınız tarayıcının güncel olduğundan emin olun.
