### ISSUE TITLE
Arayüzü kolay bir uygulama

### ISSUE THREAD

**Issue by keoma8134** [IBAX-io/go-ibax#81]
### Clear and concise description of the problem

IBAX için sizce arayüzü kolay anlaşılabilir bir uygulama nasıl olur?

### Suggested solution

Bence olmalıdır

### Alternative

Her kesin anlayabileceği kolay bir uygulama

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Sergen3535** [comment]
Türkçe dil seçeneği istiyoruz,oldukça kalabalıgiz

**Comment by ysfcndgr** [comment]
Arayüzümüz gayet sade ve anlaşılabilirdir.
