### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Abdullahoda** [IBAX-io/go-ibax#812]
### Describe the bug

When I log in with the phone in Weaver, the texts overlap and do not fit on the screen. It needs to be renewed, it is difficult to create an ecosystem from here

### Reproduction

![Screenshot_20220125_215708_com android chrome](https://user-images.githubusercontent.com/97207588/151066753-9726945f-d797-4be7-b545-289d62bb0527.jpg)
![Screenshot_20220125_215633_com android chrome](https://user-images.githubusercontent.com/97207588/151066770-5d977ecb-657e-4ed0-bca3-07cffaf73378.jpg)

### System Info

```shell
Weaver
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Enggun333** [comment]
I think enough knowledge

**Comment by DiamondG3m** [comment]
I agree with you, is there possible peaceful resolution?

**Comment by ibaxio** [comment]
Weaver is an IDE for developers, and we recommend that you use it on a PC-based browser. You can also use the desktop version (MacOS, Windows, Linux) by packaging the source code.

Weaver source code: https://github.com/IBAX-io/weaver.ibax.io
