### ISSUE TITLE
about some updates

### ISSUE THREAD

**Issue by lupo203** [IBAX-io/go-ibax#816]
### Clear and concise description of the problem

the project needs a more colorful site, it should work more on marketing, there are also users who have problems with connecting some wallets and have private key problems, also the project should not hide itself, it should be more transparent with its investors and team to the community

### Suggested solution

Connection problems with the site should not be resolved and all kinds of security measures should be increased.

### Alternative

wallet numbers, meaningless letters and numbers and the phrase ibx at the beginning may be more distinguished

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by BadAssKyle** [comment]
Thank you for your suggestion, we totally agree with you, can you provide us with a more detailed print screen? That way our product manager can see it. Thank you again for your kind support.
