### ISSUE TITLE
Keyi kaydetmeyi unuttum

### ISSUE THREAD

**Issue by Mytharoow** [IBAX-io/go-ibax#823]
### Describe the bug

Cüzdanı açtıktan sonra keyi kaydetmeyi unuttum ve hatırlamıyorum napmam gerekiyor bunun için 

### Reproduction

Çoğaltmak gerekiyor 

### System Info

```shell
Key şifre hatırlamıyorum
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Grkmkgl** [comment]
Yenisini ac

**Comment by Cryssbat** [comment]
bende cüzdanı açtım 12 kelimeyi nasıl olduysa yedeklemeyi unutmuşum, yeni cüzdan açtım ama işlem detaylarında o adresim gözüküyor 25 bine yakın ibax puanım var ha bu arada cüzdan şuan açık pozisyonda ?

![Ekran Alıntısı](https://user-images.githubusercontent.com/98237687/151127493-9b4a1a9e-dfd1-436b-a015-732b34aae8e7.PNG)
r

**Comment by ibaxio** [comment]
The password is used to encrypt your private key and allow easy access to your account
IBAX does not store your private key, so the private key associated with the password will be stored in your browser's cookie.
When you clear the cookie or use a new browser to access your IBAX account, you will need to import your helper notes and encrypt them again with your password
Of course you can also regenerate an IBAX account and re-encrypt it with a password

hint：

Take care of your private key (account seed)
Take care of your public key
Take care of your password
Take care of your wallet address

Lütfen bu tartışmaya bakın: #62 

Please refer to this discussion:  #62
