### ISSUE TITLE
Matemask cüzdan ile bağlantı.

### ISSUE THREAD

**Issue by Sercio33** [IBAX-io/go-ibax#852]
### Clear and concise description of the problem

Matemask cüzdan ile bağlantılı kurulmalı ve dağıtılan coinlerin oraya çekimi sağlanmalı.

### Suggested solution

Mobil uygulama çıkartılmalı ve daha kolay ve anlaşılır bir şekilde kullanıma açılmalıdır.

### Alternative

Mobil uygulama en kısa sürede çıkartılmalı ve matemask ile bağlantı kurulmalı.

### Additional context

Yok.

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ibaxio** [comment]
Chrome browser plug-in (just like Matemask, etc) and Web3 of IBAX Network in our development.
