### ISSUE TITLE
İBAX, Which networks and projects will it collaborate with for metaverse data storage operations?

### ISSUE THREAD

**Issue by Seyitreyhan** [IBAX-io/go-ibax#878]
### Clear and concise description of the problem

How will the metaverse data be stored frequently and systematically, will it work integrated with web3 technology and be a creation of the ibax infrastructure, or will it be a collaboration with proven projects in this field?

### Suggested solution

A storage area made on the İbax infrastructure will make us much stronger.

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Seyitreyhan** [comment]
Combination of datastore web3 and metaverse and NFT staking

**Comment by ibaxio** [comment]
Yes, you are right.

Real-world mining is the normal hardware mining. Most importantly, it serves and stores data for applications in the IBAX ecosystem. It ensures the ability of IBAX Network to provide stable global services. By reserving 40% of IBAX Network coins to reward high-performance servers, IBAX attracts Mint Nodes and ensures long-term and stable node services for the network.

Please read IBAX Network Whitepaper: https://bit.ly/3pZHrj4
