### ISSUE TITLE
Cüzdandan atma problemi

### ISSUE THREAD

**Issue by furkanygt12** [IBAX-io/go-ibax#93]
### Describe the bug

Sürekli hesabımdan atıyor ve puanlar gözükmüyor

### Reproduction

Error mesage

### System Info

```shell
System
```

### Logs

```shell
go-ibax
```

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't [already an issue](https://github.com/IBAX-io/go-ibax/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/IBAX-io/go-ibax/discussions) or join our [Discord Chat Server](https://discord.com/invite/zRX6Mwafya).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by BadAssKyle** [comment]
Retweet tasks hit the Twitter API's monthly limit for our developer accounts, so some users won't be able to earn IBAX points
