### ISSUE TITLE
IBAX WALLET

### ISSUE THREAD

**Issue by kemalumurr** [IBAX-io/go-ibax#96]
### Clear and concise description of the problem

IBAX cüzdanlarını kaybedenler için bir geri dönüşüm seçeneği olsun.Birçok kişi bu durumdan mağdur durumda.

### Suggested solution

E-mail gönderilen kod ile cüzdanlara yeniden ulaşım olsun.Ya da telefon ve e-posta doğrulaması ile bilgiler e-postaya gönderilsin

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ysfcndgr** [comment]
Mümkün değil.
