### ISSUE TITLE
Ibax wallet

### ISSUE THREAD

**Issue by Turbolaz61** [IBAX-io/go-ibax#97]
### Clear and concise description of the problem

If the ibox wallet application comes to the play store, I foresee that there will be more demand because it is very difficult to use ibox through the google page.

### Suggested solution

Obox wallet 

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ysfcndgr** [comment]
IBAX ekibi bu konu hakkında en yakın sürede geliştirme yapacaktır.
