### ISSUE TITLE
Ibax puan dağılımı githup

### ISSUE THREAD

**Issue by Efsane4167** [IBAX-io/go-ibax#999]
### Clear and concise description of the problem

Ibax da puan 8c8n githubda ne yapilmasi gerektigini net aciklamasi yok. Yorum cok fazla yapana mi veriliyor.githup olayini cozemedim gitti

### Suggested solution

Github platformunda ibax ile ilgili nasil puan yapicaz anlatilmasi gerek

### Validations

- [X] Read the [docs](https://docs.ibax.io).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Rdagci1997** [comment]
Sanırım konu açmanız ve tartışma yaratmanız gerek

**Comment by Gazarta** [comment]
Bende hiç anlamadım

**Comment by tokmakci53** [comment]
birisi anlatsa güzel olur

**Comment by ceyhannnburak** [comment]
ödül soruları varmış ama nerde olduğu ve nasıl kazanacağımızı bilmiyoruz. Yeterli açıklama yok.

**Comment by Alibey6324** [comment]
Thank you

**Comment by Davut4** [comment]
Tm

**Comment by Githubcem** [comment]
Kripto tugay youtube kanalı var 
https://youtu.be/Z_ToGMnH8W4
 Biraz da olsa Bilgi sahibi olunabilir.
